### ISSUE TITLE
Migrate to duniter organization?

### ISSUE THREAD

**Issue by M5oul** [mmuman/duniter-map#3]
I sent you an invitation to the organization.

**Comment by mmuman** [comment]
Good idea!

**Comment by M5oul** [comment]
It could be done now that you are a member of duniter organization.

**Comment by mmuman** [comment]
I wanted to close existing tickets but they should be migrated along with it anyway.

**Comment by mmuman** [comment]
hmm
> You don’t have the permission to create repositories on duniter

**Comment by mmuman** [comment]
I've transfered it to you so you can move it to the org then.

**Comment by M5oul** [comment]
Done.
