### ISSUE TITLE
Adresse inconnue

### ISSUE THREAD

**Issue by JOduMonT** [mmuman/duniter-map#4]
Bonjour;

Je suis votre projet depuis les touts début;
j'avais été enthousiasmé au début avec la première version et l'idée de renommé le truc duniter m'avait laissé dubitatif. Ensuite par l'entremise de YunoHost je me suis tenu plus ou moins à jour de vos développement pour ... finir par me créer un compte... 

Je tente de préciser mon lieu de résidence sur  
https://www.gchange.fr/#/app/wallet/profile/edit  
et j'ai le message d'erreur : _Adresse inconnue_  

J'habite au [tel que demandé : Code Postal, Ville, Pays] : 1260, Nyon, Suisse
lorsque j'entre ces infos la page les traduits par = Nyon, 1260, Switzerland ce qui demeure valide à mes yeux.

![image](https://user-images.githubusercontent.com/5204724/34900626-ebad1adc-f801-11e7-8e36-4dd026f69765.png)
_la carte pointe a quelques centaine de mètre de chez moi_

Je sais que c'est un nouveau cartier et que c'est pas nécessairement référencé
par exemple : Uber a du mal avec cette adresse ;)

ma proposition est; est-ce possible de quand même proposer mon adresse et de la faire valider par les utilisateurs que je fréquenterai par votre réseau

un peu comme ce qui se fait avec les clé PGP et leur notion de trustability.

Anyway;; tenez-moi au courant de ce que je peux faire pour ce problème

merci!

Jonathan

**Comment by mmuman** [comment]
Bonjour, bienvenue dans Duniter alors!

Le ticket me semble être sur le mauvais projet, duniter-map ne sert qu'à insérer une carte dans un site web, et n'a rien à voir avec le code de gchange.

D'après le "à propos" du site, il s'agit de ce dépot : 
https://github.com/duniter-gchange/gchange-client

A noter, pour les projets du groupe github duniter, nous sommes en train de migrer vers [notre propre gitlab](https://git.duniter.org/public).

Je pense qu'il s'agit juste d'un manque dans la base de données utilisée pour la correspondance adresses-coordonnées, probablement juste une mise à jour à faire. Une autre possibilitée serait de permettre d'entrer les latitudes/longitudes directement.
